Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.io import arff

data = arff.loadarff('messidor_features.arff')
df = pd.DataFrame(data[0])

df
------------------


[0;31m[0m
[0;31mFileNotFoundError[0mTraceback (most recent call last)
[0;32m<ipython-input-3-4da89ae45f84>[0m in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [0;32mfrom[0m [0mscipy[0m[0;34m.[0m[0mio[0m [0;32mimport[0m [0marff[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mdata[0m [0;34m=[0m [0marff[0m[0;34m.[0m[0mloadarff[0m[0;34m([0m[0;34m'messidor_features.arff'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mdf[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mdata[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/scipy/io/arff/_arffread.py[0m in [0;36mloadarff[0;34m(f)[0m
[1;32m    798[0m         [0mofile[0m [0;34m=[0m [0mf[0m[0;34m[0m[0;34m[0m[0m
[1;32m    799[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 800[0;31m         [0mofile[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mf[0m[0;34m,[0m [0;34m'rt'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    801[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    802[0m         [0;32mreturn[0m [0m_loadarff[0m[0;34m([0m[0mofile[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'messidor_features.arff'

